# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingCouple',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_name', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('email', models.EmailField(blank=True, default='', max_length=64)),
                ('phone', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingGuest',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('food', models.IntegerField(choices=[(1, 'Normalne'), (2, 'Wegetariańskie')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(blank=True, max_length=200)),
                ('church_address', models.CharField(blank=True, max_length=200)),
                ('church_view', models.CharField(blank=True, max_length=300)),
                ('premises_name', models.CharField(blank=True, max_length=200)),
                ('premises_address', models.CharField(blank=True, max_length=200)),
                ('premises_view', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AccompanyingPerson',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('food', models.IntegerField(choices=[(1, 'Normalne'), (2, 'Wegetariańskie')])),
                ('companion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guests.WeddingGuest')),
            ],
        ),
    ]
