# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingcouple',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
