# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.IntegerField()),
                ('food', models.IntegerField(choices=[(1, 'Normalne'), (2, 'Wegetariańskie')])),
            ],
        ),
    ]
