# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingcouple',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='weddingcouple',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='weddingcouple',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='weddingcouple',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
