# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_weddingguest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccompanyingPerson',
            fields=[
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('food', models.IntegerField(choices=[(1, 'Normalne'), (2, 'Wegetariańskie')])),
                ('companion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guests.WeddingGuest')),
            ],
        ),
    ]
