# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20180330_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompanyingperson',
            name='food',
            field=models.CharField(choices=[('Normalne', 'Normalne'), ('Wegetariańskie', 'Wegetariańskie')], max_length=64),
        ),
        migrations.AlterField(
            model_name='weddingguest',
            name='food',
            field=models.CharField(choices=[('Normalne', 'Normalne'), ('Wegetariańskie', 'Wegetariańskie')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='weddinginfo',
            name='church_view',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='weddinginfo',
            name='premises_view',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
