# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20180325_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingguest',
            name='email',
            field=models.EmailField(blank=True, max_length=64),
        ),
    ]
