# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guests', '0003_auto_20180325_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingguest',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
