# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_accompanyingperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=200)),
                ('church_address', models.CharField(max_length=200)),
                ('church_view', models.CharField(max_length=300, null=True)),
                ('premises_name', models.CharField(max_length=200)),
                ('premises_address', models.CharField(max_length=200)),
                ('premises_view', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
