# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guests', '0004_weddinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingcouple',
            name='id',
        ),
        migrations.AddField(
            model_name='weddingcouple',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
