# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_auto_20180322_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingcouple',
            name='email',
            field=models.EmailField(max_length=64),
        ),
    ]
