# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_auto_20180323_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingcouple',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='weddingcouple',
            name='email',
            field=models.EmailField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='weddingcouple',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='weddingcouple',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
